
server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: damian
    password: 0710
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
