events {}

http {
  upstream user_service {
    server user-creation-service:8080;
    server user-reading-service:8081;
    server user-update-service:8082;
    server login-service:8083;
  }

  upstream subject_service {
    server subject-creation-service:3006;
    server subject-reading-service:3007;
  }

  upstream section_service {
    server section-creation-service:3010;
    server section-reading-service:3011;
  }

  upstream enrollment_service {
    server enrollment-creation-service:3016;
    server enrollment-reading-service:3020;
  }

  server {
    listen 80;

    location /users/ {
      proxy_pass http://user_service/;
    }

    location /subjects/ {
      proxy_pass http://subject_service/;
    }

    location /sections/ {
      proxy_pass http://section_service/;
    }

    location /enrollments/ {
      proxy_pass http://enrollment_service/;
    }
  }
}
