<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DeleteUserService"
  targetNamespace="http://www.globalenrollment.com/delete"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:tns="http://www.globalenrollment.com/delete"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

  <message name="deleteUserRequest">
    <part name="id" type="xsd:string"/>
  </message>

  <message name="deleteUserResponse">
    <part name="message" type="xsd:string"/>
  </message>

  <portType name="DeleteUserPort">
    <operation name="deleteUser">
      <input message="tns:deleteUserRequest"/>
      <output message="tns:deleteUserResponse"/>
    </operation>
  </portType>

  <binding name="DeleteUserBinding" type="tns:DeleteUserPort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="deleteUser">
      <soap:operation soapAction="deleteUser"/>
      <input>
        <soap:body use="literal" namespace="http://www.globalenrollment.com/delete"/>
      </input>
      <output>
        <soap:body use="literal" namespace="http://www.globalenrollment.com/delete"/>
      </output>
    </operation>
  </binding>

  <service name="DeleteUserService">
    <port name="DeleteUserPort" binding="tns:DeleteUserBinding">
      <soap:address location="http://localhost:3004/delete"/>
    </port>
  </service>
</definitions>
