<?xml version="1.0" encoding="utf-8"?>
<definitions name="PasswordService"
             targetNamespace="http://www.globalenrollment.com/password"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.globalenrollment.com/password"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <message name="changePasswordRequest">
        <part name="username" type="xsd:string"/>
        <part name="oldPassword" type="xsd:string"/>
        <part name="newPassword" type="xsd:string"/>
    </message>

    <message name="changePasswordResponse">
        <part name="message" type="xsd:string"/>
    </message>

    <portType name="PasswordChangePort">
        <operation name="changePassword">
            <input message="tns:changePasswordRequest"/>
            <output message="tns:changePasswordResponse"/>
        </operation>
    </portType>

    <binding name="PasswordChangeBinding" type="tns:PasswordChangePort">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="changePassword">
            <soap:operation soapAction="changePassword"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="PasswordChangeService">
        <documentation>Servicio para cambio de contraseña</documentation>
        <port name="PasswordChangePort" binding="tns:PasswordChangeBinding">
            <soap:address location="http://localhost:3002/password"/>
        </port>
    </service>
</definitions>