<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.globalenrollment.com/role"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             name="RoleAssignmentService"
             targetNamespace="http://www.globalenrollment.com/role">

  <types>
    <xsd:schema targetNamespace="http://www.globalenrollment.com/role">
      <xsd:element name="assignRole">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="role" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name="assignRoleResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="message" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types>

  <message name="assignRoleRequest">
    <part name="parameters" element="tns:assignRole"/>
  </message>
  <message name="assignRoleResponse">
    <part name="parameters" element="tns:assignRoleResponse"/>
  </message>

  <portType name="RoleAssignmentPort">
    <operation name="assignRole">
      <input message="tns:assignRoleRequest"/>
      <output message="tns:assignRoleResponse"/>
    </operation>
  </portType>

  <binding name="RoleAssignmentBinding" type="tns:RoleAssignmentPort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="assignRole">
      <soap:operation soapAction="assignRole"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="RoleAssignmentService">
    <port name="RoleAssignmentPort" binding="tns:RoleAssignmentBinding">
      <soap:address location="http://localhost:3003/assign-role"/>
    </port>
  </service>
</definitions>
