version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: userdb
    environment:
      POSTGRES_USER: damian
      POSTGRES_PASSWORD: 0710
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  user-reading-service:
    build: .
    depends_on:
      - postgres
    ports:
      - "8081:8081"
volumes:
  pgdata:
